### ISSUE TITLE
Similarité entre vos supports et la documentation `utilitR`

### ISSUE THREAD

**Issue by oliviermeslin** [juba/tidyverse#5]
Bonjour,

D'abord, un grand merci, et un grand bravo pour la qualité de vos supports!

Voici en quelques mots ce qui m'amène à vous écrire: la documentation à laquelle je contribue présente des similarités avec la vôtre car nous avons repris puis reformulé des passages de vos supports, et nous voulons nous assurer que cela ne vous pose pas de problème.

Je travaille à l'Insee et suis l'un des mainteneurs du projet de documentation `utilitR` (www.utilitr.org). Ce projet vise à produire une documentation sur `R` qui soit adaptée aux besoins et aux cas d'usage des agents de l'Insee. Comme nous avons souhaité nous appuyer le plus possible sur les ressources existantes sur `R` en français, nous avons repris (copié/collé) des passages de votre introduction au _tidyverse_ dans notre documentation (nous avons également repris des passages des [formations du MTES](https://mtes-mct.github.io/parcours-r/)), en référençant évidemment les sources. Ces reprises touchent principalement les _packages_ `dplyr`, `tidyr`, `stringr` et `ggplot2`.

Toutefois, il s'est avéré un peu plus tard que la licence de votre documentation n'était pas compatible avec celle de notre projet (Licence Ouverte 2.0, qui est plus ou moins le seul choix pour les administrations). Nous avons donc réécrit largement les parties que nous avions reprises de vos supports: les textes sont différents et tous les exemples ont été modifiés. De notre point de vue, les deux documentations sont maintenant notablement différentes, malgré quelques similarités.

Nous tenons néanmoins à vous le signaler, afin que vous puissiez juger par vous-même du degré de similarité. Si certains passages de notre documentation vous paraissent encore trop proches de vos supports, n'hésitez pas à nous le signaler sur le [dépôt](https://github.com/InseeFrLab/utilitR), nous vous proposerons des solutions. Je suis disponible pour discuter avec vous si vous le souhaitez (sur Grrr/Slack par exemple).

Merci encore pour le travail que vous faites!

Olivier Meslin

**Comment by juba** [comment]
Bonjour,

Le fait que vous repreniez des passages de mon document ne me pose évidemment aucun problème du moment que la source est créditée, bien au contraire je suis toujours très content si mon travail peut être utile à d'autres.

Je suis un peu embêté que vous ayiez dû réécrire des passages à cause de mon choix de licence. J'imagine que c'est l'aspect "partage dans les mêmes conditions" qui posait problème ? Est-ce que je n'aurais pas pu vous accorder une "dérogation" vous permettant de réutiliser des extraits tels quels ?

Merci en tous cas pour votre message et bravo pour votre travail de documentation !

**Comment by oliviermeslin** [comment]
Merci pour votre message. La référence de vos supports figure évidemment dans les références de chaque fiche (à la fin).

Merci aussi de proposer un arrangement avec la licence, mais nous tenons à être irréprochables sur ce point (car beaucoup de gens à l'Insee ne prennent pas ce sujet au sérieux). Par ailleurs, réécrire les passages repris a été finalement très utile car cela a permis de préciser des choses, et de faire que la documentation soit la plus adaptée possible aux cas d'usages à l'Insee. 

Pour information, le lancement officiel d'`utilitR` a lieu la semaine prochaine: https://www.utilitr.org/conferences/decouverte-utilitr/

**Comment by juba** [comment]
J'ai vu passer l'annonce de la journée de lancement sur grrr, je vais voir si je peux faire un tour. Tant mieux en tous cas si la réécriture n'a pas trop été une perte de temps. En tous cas si le cas de figure se présente à nouveau n'hésitez pas à me le signaler.

Enfin, si je peux me permettre une petite suggestion (désolé ça va faire très autopromotion) : pour votre partie sur ACP / ACM / AFC, j'ai un package nommé `explor` qui permet d'explorer les résultats de ces analyses via une interface et des graphiques interactifs : 

https://juba.github.io/explor/

Ça pourrait peut-être intéresser certain.es lecteurs.trices ?

Bonne journée !

**Comment by oliviermeslin** [comment]
Merci pour l'idée de présenter `explor`, je vais tâcher de m'en souvenir pour des jours plus calme. Ceci dit, j'hésitais un peu à enlever la partie sur l'analyse de données, qui est peut-être trop spécifique par rapport au reste d'`utilitR`.

**Comment by juba** [comment]
Oui je comprends ! C'est toujours compliqué de fixer une frontière entre ce qu'on traite ou pas (si on aborde les méthodes d'analyse est-ce qu'on présente juste comment les mettre en oeuvre ou est-ce qu'on explique aussi les méthodes en elles-mêmes, etc.), et ça peut vite devenir un puits sans fond...
