### ISSUE TITLE
La macro textsf ne fonctionne pas

### ISSUE THREAD

**Issue by thombet** [juba/tidyverse#8]
Bonjour,

Merci pour le super guide !

En lisant la version HTML (https://juba.github.io/tidyverse/01-presentation.html), je me suis rendu compte que la macro `\textsf{S}` ne fonctionnait pas et n'était pas affichée.
La ligne correspondante est https://github.com/juba/tidyverse/blob/a6a63304945924d43f5649a9c900c491985b7aa9/01-presentation.qmd#L7C102-L7C111

Je ne maîtrise pas quarto donc j'ai préféré ouvrir un ticket plutôt que de proposer une correction.

**Comment by juba** [comment]
Damn, ce `\textsf{}` est un résidu de l'époque où le document n'était disponible qu'en PDF, c'est dire qu'il devait traîner là depuis un paquet d'année !

Merci d'avoir pris le temps de me signaler le problème, ça devrait désormais être corrigé.
